# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Security/Open:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Style/ExponentialNotation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false