# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'faraday-detailed_logger'
gem 'faraday-follow_redirects'
gem 'faraday-http-cache'
gem 'faraday-net_http_persistent'
gem 'faraday-retry'
gem 'ferrum'
gem 'geo_coord', require: 'geo/coord'
gem 'http'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'nokogiri'
gem 'parallel'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'terminal-table'
gem 'tilt'
gem 'webmock'
