# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'ferrum'
gem 'front_matter_parser'
gem 'geo_coord', require: 'geo/coord'
gem 'http'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'nokogiri'
gem 'parallel'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'ruby-openai'
gem 'terminal-table'
gem 'tilt'
gem 'webmock'
