name: Build Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # 5AM EST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Cache multiple paths
      uses: actions/cache@v3
      with:
        path: .cache
        key: cache-for-http-responses
    - name: Install minify
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with: # Grab the latest version
        repo: tdewolff/minify
        tag: v2.12.4 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Build docs
      run: bundle exec rake build
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
    - name: commit files
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "Github Actions Bot <jtarchie+githubbot@gmail.com>"
        # Stage the file, commit and push
        git add -A
        git commit -m "generated docs from github action"
        git push origin main
